# Quick intro to `numpy`
### MCS 275 Spring 2021 - David Dumas

This is a quick tour of some `numpy` features.  For more detail see:
* [Chapter 2 of VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
* [The numpy documentation](https://numpy.org/doc/stable/)

(We'll add more to this notebook in Lecture 26.)

In [2]:
import numpy as np
np.__version__

'1.17.4'

## Making and using arrays

[List of built-in dtypes](https://numpy.org/doc/stable/reference/arrays.scalars.html#arrays-scalars-built-in).

In [53]:
# all zeros, specified shape
np.zeros( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# all ones, specified shape
np.ones( (8,) )

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# array with every entry equal to a given constant
np.full( (3,3), 1.7 )  # shape, value

array([[1.7, 1.7, 1.7],
       [1.7, 1.7, 1.7],
       [1.7, 1.7, 1.7]])

In [7]:
A = np.ones( (4,4) )
A.ndim  # the dimension of A

2

In [8]:
A.shape # the shape of A

(4, 4)

In [9]:
A.size # the number of elements in A

16

In [10]:
A.dtype # the data type (np.ones gives float64 by default)

dtype('float64')

In [54]:
B = np.full( (2,3), 6 )  # Python int given, converted to int64
B.dtype

dtype('int64')

In [56]:
# Build array from an iterable
C = np.array( [[5,6,7,8],[9,10,11,12]] )

In [17]:
print(C.ndim)
print(C.dtype)
print(C.size)

2
int64
8


In [19]:
# np.random.random(shape) gives array of uniformly distributed
# random floats 0<=x<1
np.random.random((5,8))

array([[0.71205335, 0.92678077, 0.63782388, 0.0443609 , 0.22654121,
        0.37925262, 0.95746515, 0.47439356],
       [0.43646419, 0.60599148, 0.47297278, 0.30563332, 0.17018216,
        0.9153842 , 0.28722953, 0.20839653],
       [0.42967794, 0.33536607, 0.66756755, 0.86407176, 0.76961467,
        0.99602041, 0.97321266, 0.29357561],
       [0.61409002, 0.0338399 , 0.12149724, 0.34554109, 0.47548652,
        0.77123556, 0.90267432, 0.45335279],
       [0.57007505, 0.8445216 , 0.08838114, 0.94622915, 0.90687248,
        0.28759011, 0.94766349, 0.25547712]])

In [57]:
np.eye(5,dtype="int")  # identity matrix, specified dtype

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [59]:
np.ones((2,2),dtype="bool")  # numpy supports boolean arrays
# coerces 0 to False and 1 to True

array([[ True,  True],
       [ True,  True]])

### Arithmetic progressions

In [27]:
np.arange(3,8,0.7)  # start, stop, step.  Will not include stop.

array([3. , 3.7, 4.4, 5.1, 5.8, 6.5, 7.2, 7.9])

In [60]:
np.linspace(2,7,31)  # first, last, num_steps

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        , 3.16666667, 3.33333333, 3.5       ,
       3.66666667, 3.83333333, 4.        , 4.16666667, 4.33333333,
       4.5       , 4.66666667, 4.83333333, 5.        , 5.16666667,
       5.33333333, 5.5       , 5.66666667, 5.83333333, 6.        ,
       6.16666667, 6.33333333, 6.5       , 6.66666667, 6.83333333,
       7.        ])

## Accessing elements (indexing and slices)

In [34]:
A = np.array(range(24)).reshape((4,6))   # 0..23 in a vector, but then convert to 4x6 matrix
v = np.arange(1,5,1.2) # vector (array with ndim=1)

In [35]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [36]:
v

array([1. , 2.2, 3.4, 4.6])

In [61]:
v[1] # element at index 1 (zero-based)

2.2

In [39]:
v[-2] # second to last element

3.4000000000000004

In [62]:
A[2,0]  # row 2, column 0

13

In [42]:
A[:,2]  # column 2 of A  (remember, 0-based numbering!)
# I think of this as A[anything,2]

array([ 2,  8, 14, 20])

In [63]:
A[1,:]  # row 1 of A
# I think of this as A[1,anything]

array([ 7,  8,  9, 10, 11, 12])

In [65]:
A[1] # another way to specify row 1 of A
# missing indices are treated as ":"

array([ 7,  8,  9, 10, 11, 12])

In [44]:
A[::2,1:3]  # all rows of even index, columns 1 and 2

array([[ 1,  2],
       [13, 14]])

## Ufuncs

In [67]:
# Let's make an array to work with
A = np.array(range(1,16)).reshape((3,5))
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [68]:
1 / A  # reciprocal of each entry in the matrix

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [69]:
A**2 # square of each entry

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [70]:
np.sin(A) # apply sin() to each entry

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [72]:
# first 11 cubes
np.arange(1,12)**3  # make vector of 1..11 and then cube each entry

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331])

## Broadcasting

## Aggregation functions

## Masks